In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
from function import *
from tqdm import tqdm

warnings.simplefilter('ignore')

In [ ]:
data_path = '../1.data/'
train_file_name = 'train.csv'
test_file_name  = 'test.csv'

In [ ]:
train_df = pd.read_csv(f'{data_path}{train_file_name}')
test_df = pd.read_csv(f'{data_path}{test_file_name}')
train_df.head()

In [ ]:
non_cols = ['id', 'price']
num_cols = ['year', 'odometer']
cat_cols = [col for col in train_df.columns if col not in non_cols + num_cols]

In [ ]:
train_df = creansing_dataset(train_df)
test_df = creansing_dataset(test_df)

In [ ]:
def check_data_bias(comb_n):
    agg_l = []

    comb_list = itertools.combinations(cat_cols, comb_n)
    for comb in tqdm(comb_list):
        comb = list(comb)
        gcomb = comb + ['id']
        info_df = \
            pd.concat([
                train_df[gcomb].groupby(comb)['id'].count().rename('train'), 
                test_df[gcomb].groupby(comb)['id'].count().rename('test')
            ], axis=1).reset_index()

        agg_l.append([
            '-'.join(comb),
            info_df[info_df['test'].isnull()]['train'].sum(),
            info_df[info_df['train'].isnull()]['test'].sum()
        ])

    return pd.DataFrame(agg_l, columns=['comb', 'only_train', 'only_test'])

In [52]:
comb2_df = check_data_bias(2)
display(comb2_df.sort_values('only_train', ascending=False).head(10))
display(comb2_df.sort_values('only_test', ascending=False).head(10))

66it [00:01, 45.32it/s]

                   comb  only_train  only_test
0   region-manufacturer      1871.0     1905.0
8           region-type       661.0      674.0
9    region-paint_color       607.0      605.0
4   region-title_status       330.0      333.0
20   manufacturer-state       275.0      218.0
2      region-cylinders       242.0      218.0
1      region-condition       206.0      270.0
7           region-size       170.0      178.0
3           region-fuel       138.0      127.0
5   region-transmission       124.0      106.0

                   comb  only_train  only_test
0   region-manufacturer      1871.0     1905.0
8           region-type       661.0      674.0
9    region-paint_color       607.0      605.0
4   region-title_status       330.0      333.0
1      region-condition       206.0      270.0
20   manufacturer-state       275.0      218.0
2      region-cylinders       242.0      218.0
7           region-size       170.0      178.0
3           region-fuel       138.0      127.0
5   region-transmission       124.0      106.0

In [51]:
comb3_df = check_data_bias(3)
display(comb3_df.sort_values('only_train', ascending=False).head(10))
display(comb3_df.sort_values('only_test', ascending=False).head(10))

220it [00:08, 27.07it/s]

                                comb  only_train  only_test
8    region-manufacturer-paint_color      7215.0     7119.0
7           region-manufacturer-type      5605.0     5582.0
0      region-manufacturer-condition      4846.0     4924.0
6           region-manufacturer-size      4101.0     4034.0
52           region-type-paint_color      3960.0     4017.0
3   region-manufacturer-title_status      3860.0     3878.0
1      region-manufacturer-cylinders      3753.0     3806.0
4   region-manufacturer-transmission      3542.0     3588.0
5          region-manufacturer-drive      3473.0     3404.0
17      region-condition-paint_color      2558.0     2481.0

                                comb  only_train  only_test
8    region-manufacturer-paint_color      7215.0     7119.0
7           region-manufacturer-type      5605.0     5582.0
0      region-manufacturer-condition      4846.0     4924.0
6           region-manufacturer-size      4101.0     4034.0
52           region-type-paint_color      3960.0     4017.0
3   region-manufacturer-title_status      3860.0     3878.0
1      region-manufacturer-cylinders      3753.0     3806.0
4   region-manufacturer-transmission      3542.0     3588.0
5          region-manufacturer-drive      3473.0     3404.0
16             region-condition-type      2277.0     2506.0

In [53]:
comb4_df = check_data_bias(4)
display(comb4_df.sort_values('only_train', ascending=False).head(10))
display(comb4_df.sort_values('only_test', ascending=False).head(10))

495it [00:27, 17.83it/s]

                                            comb  only_train  only_test
42          region-manufacturer-type-paint_color     13074.0    13071.0
7      region-manufacturer-condition-paint_color     12071.0    12068.0
40          region-manufacturer-size-paint_color     10901.0    10828.0
15     region-manufacturer-cylinders-paint_color     10820.0    10699.0
6             region-manufacturer-condition-type     10232.0    10283.0
37         region-manufacturer-drive-paint_color     10204.0    10181.0
33  region-manufacturer-transmission-paint_color     10028.0     9952.0
28  region-manufacturer-title_status-paint_color      9771.0     9760.0
39                 region-manufacturer-size-type      8866.0     8904.0
14            region-manufacturer-cylinders-type      8762.0     8825.0

                                            comb  only_train  only_test
42          region-manufacturer-type-paint_color     13074.0    13071.0
7      region-manufacturer-condition-paint_color     12071.0    12068.0
40          region-manufacturer-size-paint_color     10901.0    10828.0
15     region-manufacturer-cylinders-paint_color     10820.0    10699.0
6             region-manufacturer-condition-type     10232.0    10283.0
37         region-manufacturer-drive-paint_color     10204.0    10181.0
33  region-manufacturer-transmission-paint_color     10028.0     9952.0
28  region-manufacturer-title_status-paint_color      9771.0     9760.0
39                 region-manufacturer-size-type      8866.0     8904.0
14            region-manufacturer-cylinders-type      8762.0     8825.0